version: '3'
services:
     reactdev:
        build:
           context: .
           dockerfile: Dockerfile.dev
        ports:
        - 3000:3000
        volumes:
        - /app/node_modules
        - .:/app
     reacttest:
        build:
           context: .
           dockerfile: Dockerfile.dev
        volumes:
        - /app/node_modules
        - .:/app
        command:
        - "npm"
        - "run"
        - "test"

