version: '3'
services:
     reacttest:
        build:
           context: .
           dockerfile: Dockerfile.test
        ports:
        - 3000:3000
        volumes:
        - /app/node_modules
        - .:/app

